### ISSUE TITLE
Crash when reading server.properties

### ISSUE THREAD

**Issue by fenhl** [PistonDevelopers/hematite_server#101]
When `server.properties` is missing, the server seems to start correctly, but when it exists, it panics at an array index.

```
$ hematite_server
INFO - hematite server
thread '<main>' panicked at 'index out of bounds: the len is 1 but the index is 1', ../src/libcollections/vec.rs:1106
$ cat server.properties
server-port=25566
```

**Comment by toqueteos** [comment]
Good catch!

**Comment by fenhl** [comment]
Any idea what might cause it?

**Comment by toqueteos** [comment]
I'm checking [src/proto/properties.rs](https://github.com/PistonDevelopers/hematite_server/blob/master/src/proto/properties.rs) for index ops but I haven't found a clue yet.

**Comment by toqueteos** [comment]
@fenhl Found it! Apparently `splitn` isn't doing it's thing: http://is.gd/RkWXrx

`splitn("server-port=25565", 1)` returns `["server-port=25565"]` so https://github.com/PistonDevelopers/hematite_server/blob/master/src/proto/properties.rs#L53 fails because there's no `parts[1]`.

**Comment by fenhl** [comment]
It needs to be changed to `.splitn(2, '=')`. The “n” in splitn is the number of parts, not the number of splits.

**Comment by toqueteos** [comment]
@fenhl That's right! Do you want to patch it and add a test case for it?

**Comment by fenhl** [comment]
I can patch it, not sure about the test case though.

**Comment by toqueteos** [comment]
Nvm, you patch it I add the test.
