### ISSUE TITLE
Update to new io

### ISSUE THREAD

**Issue by fenhl** [PistonDevelopers/hematite_server#15]
Since `std::old_io` is now spewing deprecation warnings, we should update to the new `std::io`. I'd say we should merge #10 and #14 now (regardless of any remaining problems), then switch over to new `io` and worry about cleaning up `types::nbt` when that's done.

**Comment by toqueteos** [comment]
:+1: I'm ok with this. EDIT: If no PR is sent, I'll try to send one on Sunday.

**Comment by toqueteos** [comment]
- [ ] `MemReader` -> `Cursor<Vec<u8>>` or `Cursor<&[u8]>`. Used only on tests.
- [ ] No endianness support, must use [byteorder](http://burntsushi.net/rustdoc/byteorder/) crate.

**Comment by fenhl** [comment]
I'm almost done with porting to `byteorder`. Haven't touched the tests yet.
