### ISSUE TITLE
AttachEntity field names

### ISSUE THREAD

**Issue by toqueteos** [PistonDevelopers/hematite_server#25]
[AttachEntity](http://wiki.vg/Protocol#Attach_Entity) packet has led to a heated discussion on IRC (#hematite).

![AttachEntity Protocol Spec](http://i.imgur.com/wXpwgrU.png)

My naming proposal is (order is important, this is packets code):

``` rust
struct AttachEntity{
    what: i32, // maybe `who` is better suited for this instead of `what`
    to: i32,
    leash: bool
}
```

**Is it ambiguous for you this way?**
Let the discussion begin...

/cc @bvssvni @eddyb @fenhl @kvark

**Comment by fenhl** [comment]
``` rust
AttachEntity {
    riding_eid: i32,
    vehicle_eid: i32,
    leash: bool
}
```

The wording “_what_ is leashed to _to_” is ambiguous, is could be `struct AttachEntity { to: i32, what: i32, leash: bool }` and make just as much sense. Essentially, the English verb “attach” represents a symmetrical relation, but the “riding/leashed” relation indicated by this packet is directional, so we need different naming.

**Comment by fenhl** [comment]
After the discussion on IRC, can we close this?

**Comment by kvark** [comment]
@toqueteos sorry pal, I'm not really into hematite networking, at least for now I'm only helping with rendering.

**Comment by toqueteos** [comment]
@kvark Nvm, I mixed cc.

@fenhl Yes, we can. Closing this.
