### ISSUE TITLE
Impl Chat type

### ISSUE THREAD

**Issue by toqueteos** [PistonDevelopers/hematite_server#27]
It would enable 8 packets:
- `ChatMessage` (0x02)
- `OpenWindow` (0x2d) Custom
- `UpdateSign` (0x33)
- `Disconnect` (0x40)
- `PlayerListHeaderFooter` (0x47)
- `ChatMessage` (0x01)
- `UpdateSign` (0x12)
- `Disconnect` (0x00)
# Encoding

A custom encoder is required because of `extra` field and how `rustc-serialize` encodes `Option<T>` values, it writes `key: null` instead of skipping keypair.
# Decoding (Parsing)

In order to parse Chat contents we need to use the streaming JSON Parser found in `rustc_serialize::json::Parser`, it spits out `rustc_serialize::json::JsonEvent`s.

Reference: http://wiki.vg/Chat

Here's some starting code for those interested in tinkering with it:

``` rust
extern crate "rustc-serialize" as rustc_serialize;

use rustc_serialize::json::{JsonEvent, Parser};

fn main() {
    let blob = r#"{
        "text": "Hello world",
        "translate": "multiplayer.player.joined",
        "with": [
            "thinkofdeath"
        ],
        "score": {
            "name": "<playername>",
            "objective": "<objectivename>"
        },
        "selector": "",
        "extra": [
            "Testing",
            {"translate":"demo.day.2"}
        ],
        "bold":true,
        "italic":false,
        "underlined": false,
        "strikethrough": false,
        "obfuscated": false,
        "color":"red",
        "clickEvent":{
            "action":"run_command",
            "value": "/time set day"
        },
        "hoverEvent": {
            "action":"show_text",
            "value": "Hello"
        },
        "insertion": "Hello world"
    }"#;

    let mut parser = Parser::new(blob.chars());
    loop {
        let evt = match parser.next() {
            Some(e) => e,
            None => { break; }
        };
        println!("{:?} {:?}", parser.stack().top(), evt);
    }
}
```

**Comment by toqueteos** [comment]
I've been tinkering around with https://github.com/toqueteos/hematite_server_ugly and found that vanilla client ~~doesn't use this format at all for client-sent messages~~ uses both old and new chat formatting (`§` and JSON). :expressionless:

**Comment by atheriel** [comment]
I've started working on some pieces for this. Should have them up by the end of the day.
