### ISSUE TITLE
Beta channel

### ISSUE THREAD

**Issue by toqueteos** [PistonDevelopers/hematite_server#75]
So... there's beta channel now! That's both good and bad for us because some parts of our code rely on features not yet stabilized:
- [ ] `std::iter::AdditiveIterator` -> `core` feature.
- [ ] `extern crate test` -> `test` feature.

**Feel free to modify this list so we can track unstability across the project.**

How are we gonna deal with this?

/cc @atheriel @bvssvni @eddyb @fenhl

**Comment by fenhl** [comment]
I would suggest creating a branch where we attempt to migrate the codebase to stable Rust.

**Comment by bvssvni** [comment]
What should we call it? "rust-beta"?

**Comment by fenhl** [comment]
Maybe `rust-stable`?

**Comment by toqueteos** [comment]
What would making a branch help us with? It seems there's not that much we can do until core dev team stabilize all of what we need unless we are willing to copy, without #[unstable], a bunch of std's code.

**Comment by fenhl** [comment]
It would allow us to stabilize code on the stable branch while continuing current development on master.

**Comment by atheriel** [comment]
I think this might be an easy issue to fix right now just by getting off
the unstable APIs -- we can fix the iterator one by using a fold, and the
test crate is only used for benchmarking (which could be hidden behind a
configuration flag, or even removed for the time being).

Alternatively, a stable branch sounds appropriate to me.

**Comment by fenhl** [comment]
The two issues are by far not the only ones, hence my suggestion to work on this on a branch.

**Comment by fenhl** [comment]
I have updated .travis.yml to reflect the fact that master is only supposed to build on nightly.
