### ISSUE TITLE
Move hematite-nbt into its own repo

### ISSUE THREAD

**Issue by fenhl** [PistonDevelopers/hematite_server#79]
It's a separate crate so it should be a separate repo. It would also be a further step toward publishing on [crates.io](https://crates.io/).

While we do that, we should rename it to `hematite_nbt` per #68.

**Comment by toqueteos** [comment]
What's wrong with having it here? We can still publish it to crates just as gl_generator or gfx-rs do with their inner repos, can we?

**Comment by fenhl** [comment]
It's independent of the server crate. Managing it as such would also make it more discoverable.

**Comment by fenhl** [comment]
[Repo created](https://github.com/PistonDevelopers/hematite_nbt), moving content now.
