### ISSUE TITLE
Add a CONTRIBUTING file

### ISSUE THREAD

**Issue by fenhl** [PistonDevelopers/hematite_server#85]
This should include our workflow/policy of sending pull requests even if you have direct write access.

**Comment by bvssvni** [comment]
There is a CONTRIBUTING file in the piston repo https://github.com/PistonDevelopers/piston/blob/master/CONTRIBUTING.md. I added a notice about PRs.

**Comment by fenhl** [comment]
It might be useful to have a CONTRIBUTING.md here which just links to the central one.
