### ISSUE TITLE
Branch protection

### ISSUE THREAD

**Issue by fenhl** [PistonDevelopers/hematite_server#98]
Since github now has [a feature](https://github.com/PistonDevelopers/hematite_server/settings/branches/master) that lets us require status checks (i.e. Travis CI) to be passed before changes can be merged into master, we could use this to ensure a green master branch and to enforce Piston's “pull requests for everything” model.

I have been using this feature for other Rust projects and it's been very helpful. Should we enable it here as well?

**Comment by toqueteos** [comment]
PRs are one of the pillars of GitHub. While not the best thing out there for code review they are useful enough so I'm voting yes on this. The more checks for greenness, the better.

**Comment by bvssvni** [comment]
This would be nice.

**Comment by fenhl** [comment]
Branch protection and required status checks now in effect for master.
